Testing
YunoHost-Apps/zabbix_ynh pull request #23
Opened 2021-08-11 16:00 UTC by yalh76

2021-08-11 16:00 UTC, yalh76 commented
!testme

2021-08-12 20:15 UTC, yalh76 commented
!testme

2021-08-13 06:21 UTC, yalh76 commented
!testme

2021-08-14 11:48 UTC, yalh76 commented
!testme

2021-08-14 16:54 UTC, yalh76 commented
!testme

2021-08-14 21:07 UTC, yalh76 commented
!testme

2021-08-15 12:40 UTC, yalh76 commented
!testme

2021-08-15 14:18 UTC, yalh76 commented
!testme

2021-08-15 16:12 UTC, yalh76 commented
!testme

2021-08-16 19:28 UTC, yalh76 commented
!testme

2021-08-16 23:47 UTC, yalh76 commented
!testme

2021-08-17 06:20 UTC, ericgaspar requested changes

2021-08-17 06:20 UTC, ericgaspar commented on scripts/restore
> +ynh_secure_remove --file="$final_path"
Are we sure to remove the final_path here? 🤔

2021-08-17 07:27 UTC, yalh76 commented on scripts/restore
> +ynh_secure_remove --file="$final_path"
I don't know, but it was done like that => L36 `ynh_secure_remove $final_path`

2021-08-17 07:27 UTC, yalh76 commented
!testme

2021-08-17 23:21 UTC, yalh76 commented
was too difficult to make it works, I prefer to restart from scratch on https://github.com/YunoHost-Apps/zabbix_ynh/tree/example

2021-08-17 23:21 UTC, closed without merging