Testing - Packaging v2
YunoHost-Apps/zabbix_ynh pull request #68
Opened 2024-03-29 12:33 UTC by Salamandar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2024-03-29 12:33 UTC, Salamandar commented
!testme

2024-04-22 15:28 UTC, alexAubin requested changes

2024-04-22 15:28 UTC, alexAubin commented on scripts/_common.sh
>  		sid=$(curl $curlOptions \
This curl call and the previous one probably don't work anymore in private install

I'm not sure how it was supposed to work before, but anyway, ideally one should rely on ynh_local_curl which will temporarily make the app public : https://github.com/YunoHost/yunohost/blob/dev/helpers/utils#L435

2024-04-29 17:04 UTC, Thovi98 commented on manifest.toml
> +    default = false
```suggestion
    default = "visitors"
```
 `false` is not a valid value for Bookworm

2024-05-01 20:32 UTC, alexAubin commented
So TL;DR the status is : 
- this PR is working-ish on bullseye, but the private install probably is broken because there's a raw curl which doesn't properly temporarily enable visitors on the endpoint
- it doesn't work on bookworm because zabbix 5.x depends on libssl1.1 which doesn't exist anymore on bookworm. We should upgrade to 6.x probably, but as shown in https://github.com/YunoHost-Apps/zabbix_ynh/pull/46, the initial provisioning of the mysql DB changes (?) and probably a migration need to be performed ?

2024-05-01 22:00 UTC, alexAubin commented
Hmokay, I managed to fix the curl issue, let's release this and iterate for bookworm

2024-05-01 22:01 UTC, merged